language: node_js
node_js:
- 5
sudo: false
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_d66822a85ddf_key -iv $encrypted_d66822a85ddf_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- |
  chmod 600 ~/.ssh/id_rsa
  eval $(ssh-agent)
  ssh-add ~/.ssh/id_rsa
  cp .travis/ssh_config ~/.ssh/config
  git config --global user.name "haishanh"
  git config --global user.email "haishanhan@gmail.com"
  pwd
  cd themes
  git clone git@github.com:haishanh/hexo-theme-zxcvb.git zxcvb
  cd ..
  npm install hexo-cli -g
  npm --version
script:
- hexo generate
- hexo deploy
